### ISSUE TITLE
Handling no tags present yet?

### ISSUE THREAD

**Issue by mvangent** [krysopath/semver#4]
Amazing neat little tool. What do you think of handling the case where a repo has no git tag yet?

**Comment by krysopath** [comment]
the tool does not read from a git repo. instead it is fed a string via /dev/stdin, if that string is not a valid tag the behavior is not graceful, this could indeed be improved.

**Comment by mvangent** [comment]
@krysopath What about this proposal?

* If no tag is passed, throw an error with informative message
* If no tag is passed, but --first-tag flag is added to the command it will set the version 0.0.1
* If semver string is of an invalid format, throw an error with informative message?

**Comment by krysopath** [comment]
I found out how to specify signature sub keys for gitub in correct way. I merged #8 to master.
